version: '3'

services:
  allure-ui:
    image: "frankescobar/allure-docker-service-ui"
    user: 1000:1000
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://192.168.2.24:5050"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
      URL_PREFIX: "/embold/v2"
      ROUTER_BASE_NAME: "/embold/v2/test-automation"
    ports:
      - "7744:5252"

  allure:
    image: "frankescobar/allure-docker-service"
    user: 1000:1000
    environment:
      CHECK_RESULTS_EVERY_SECONDS: NONE
      KEEP_HISTORY: 1
      KEEP_HISTORY_LATEST: 12
      SECURITY_USER: ${ghuser}
      SECURITY_PASS: ${ghpass}
      SECURITY_VIEWER_USER: "redstar"
      SECURITY_VIEWER_PASS: "redstar"
      SECURITY_ENABLED: 1
      MAKE_VIEWER_ENDPOINTS_PUBLIC: 0
      EMAILABLE_REPORT_TITLE: "Embold V2: Regression Tests"
      ACCESS_TOKEN_EXPIRES_IN_DAYS: 1
      REFRESH_TOKEN_EXPIRES_IN_DAYS: 1
      URL_PREFIX: "/embold/v2"
      SERVER_URL: "http://192.168.2.24:7744/embold/v2/test-automation/projects/default/reports/latest"
    ports:
      - "5050:5050"
    volumes:
      - ./test-automation/v2/uitests/allure-results/allure-results:/app/allure-results
      - ./test-automation/v2/uitests/allure-reports:/app/default-reports